# Generated by Django 5.0.1 on 2024-01-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pics')),
                ('about', models.TextField()),
            ],
        ),
    ]
